pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        git branch: 'main', url: 'https://github.com/praveen-verma-j/Jenkins-Zero-To-Hero'
        sh 'cd kafka_demo && mvn clean build'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
