pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
       docker {
         image 'abhishekf5/maven-abhishek-docker-agent:v1'
         args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
       }
      }
      steps {
        git branch: 'main', url: 'https://github.com/praveen-verma-j/Jenkins-Zero-To-Hero'
        sh 'cd kafka_demo && mvn clean install'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
